// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwNZX0rr1qnGpCM8glMi8ZyBFsAh2CTNc',
    appId: '1:501931801163:web:6374fe53965476cff82bce',
    messagingSenderId: '501931801163',
    projectId: 'firbase-9bfba',
    authDomain: 'firbase-9bfba.firebaseapp.com',
    storageBucket: 'firbase-9bfba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuBueUaSkNR6ujyNcI_I97FI8EZIIP2CA',
    appId: '1:501931801163:android:52425877cc8cc258f82bce',
    messagingSenderId: '501931801163',
    projectId: 'firbase-9bfba',
    storageBucket: 'firbase-9bfba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXh979shFlghnbEO_Lw7V_169zXybG3U',
    appId: '1:501931801163:ios:1dad46b7f05bd56df82bce',
    messagingSenderId: '501931801163',
    projectId: 'firbase-9bfba',
    storageBucket: 'firbase-9bfba.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXh979shFlghnbEO_Lw7V_169zXybG3U',
    appId: '1:501931801163:ios:1dad46b7f05bd56df82bce',
    messagingSenderId: '501931801163',
    projectId: 'firbase-9bfba',
    storageBucket: 'firbase-9bfba.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwNZX0rr1qnGpCM8glMi8ZyBFsAh2CTNc',
    appId: '1:501931801163:web:4493e20f97af6267f82bce',
    messagingSenderId: '501931801163',
    projectId: 'firbase-9bfba',
    authDomain: 'firbase-9bfba.firebaseapp.com',
    storageBucket: 'firbase-9bfba.firebasestorage.app',
  );
}
